version: '1'
services:
  tomcat:
    build: .
    restart: "no"
    ports:
     - "8080:8080"
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
